services:
  - type: web
    name: flip-to-win-backend
    env: node
    plan: free
    region: oregon # Change to your preferred region
    buildCommand: npm ci --only=production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add disk for persistent logs
    disk:
      name: logs
      mountPath: /opt/render/project/src/logs
      sizeGB: 1
